# Shape and Reshape in numpy

# SHAPE

In [2]:
import numpy as np

var1=np.array([[1,2],[2,3]])

print(var1)
print()
print(var1.shape)#it shows shape of array [2,2]rows,column

[[1 2]
 [2 3]]

(2, 2)


In [1]:
import numpy as np

var2=np.array([1,2,3,4],ndmin=4)

print(var2)
print(var2.ndim)
print(var2.shape)#it gives output like[1,1,1,4] it means that first dimen has row 1 second has 1 row and 3rd has 1 row 
#and all have 4 columns

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


# RESHAPE

In [3]:
import numpy as np

var2=np.array([1,2,3,4,5,6])

x=var2.reshape(3,2)

print(x)
print("x dimension is",x.ndim)

print()
print(var2)
print("var2 dimension is",var2.ndim)


[[1 2]
 [3 4]
 [5 6]]
x dimension is 2

[1 2 3 4 5 6]
var2 dimension is 1


In [ ]:
import numpy as np

var2=np.array([1,2,3,4,5,6])
var2.shape=(2,3)
print(var2)
x=var2.reshape(3,2)

print(x)
print("x dimension is",x.ndim)

print()
print(var2)
print("var2 dimension is",var2.ndim)


In [12]:
import numpy as np

var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x=var2.reshape(2,3,2)
print(x)
print(x.ndim)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [19]:
#if i want to reshape 3d to 1d
import numpy as np

var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x=var2.reshape(2,3,2)
print(x)
print(x.ndim)
print("conversion from 3d to 1 d")
oned=x.reshape(-1)
print(oned)
print(oned.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
conversion from 3d to 1 d
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# WHERE:

In [2]:
#it returns index numbers of given condition
import numpy as np 
b=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
c=np.where(b<4)
print(c)

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
