# Arthemetic Operation In Numpy

# Division

In [2]:
import numpy as np
a = np.array([[2,4,6,8],[1,3,5,7]])
b = np.array([[1,2,2,2],[2,2,2,2]])
ratio = a/b
print("by function:",np.divide(a,b))
print('manually: ',ratio)


by function: [[2.  2.  3.  4. ]
 [0.5 1.5 2.5 3.5]]
manually:  [[2.  2.  3.  4. ]
 [0.5 1.5 2.5 3.5]]


# multiplication


In [10]:
import numpy as np
# multiplication

a = np.array([[2,4,6,8],[1,3,5,7]])
b = np.array([[1,1,1,1],[2,2,2,2]])
m = a*b
print(m)
print(np.multiply(a,b))

[[ 2  4  6  8]
 [ 2  6 10 14]]
[[ 2  4  6  8]
 [ 2  6 10 14]]


# ARGMAX & ARGMIN for index(max & min)

In [ ]:
import numpy as np
# ARGMAX & ARGMIN for index(max & min)
a = np.array([4,2,6,8])
print(a)

print(f"max is {np.max(a)} and its index num is {np.argmax(a)}")
print(f"min is {np.min(a)} and its index number is {np.argmin(a)}")

# MAX & MIN

In [ ]:
import numpy as np

a = np.array([2,4,6,8])

print(a)
print("min is: ",np.min(a))
print("max is:",np.max(a))


# power & sqrt

In [37]:
import numpy as np

# 1d-array
x1d = np.array([1,2,3,4,5])
y=np.power(x,2)

print('array: ',x1d)
print("power^2: ",y)
print("sqrts: ",np.sqrt(y))
print()
#2d-array
x2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
y2=np.power(x,2)
print("power^2: ",y2)
print("sqrts: ",np.sqrt(y2))

array:  [1 2 3 4 5]
power^2:  [[ 1  4  9 16 25]]
sqrts:  [[1. 2. 3. 4. 5.]]

power^2:  [[ 1  4  9 16 25]]
sqrts:  [[1. 2. 3. 4. 5.]]


# 2d  max min

In [46]:
import numpy as np


x = np.array([[2,1,3],
             [9,5,6]])     # axis = 0 represents coloumns
                           # axis = 1 represents rows
print('min: ',np.min(x,axis=1))
print('max: ',np.max(x,axis=1))
print()
print('min: ',np.min(x,axis=0))
print('max: ',np.max(x,axis=0))

min:  [1 5]
max:  [3 9]

min:  [2 1 3]
max:  [9 5 6]


# sin cos tan

In [16]:
import numpy as np

x = np.array([[0,30,45,60,90]])
c = np.cos(x)
s = np.sin(x)
t = np.tan(x)
print("cos: ",c)
print("sin: ",s)
print("tan: ",t)

#for pi use np.pi/2 or np.pi/4 etc 

cos:  [[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]]
sin:  [[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]]
tan:  [[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]]
-1.995200412208242


# subtraction 

In [54]:
import numpy as np

# subtraction of 2 arrays

a = np.array([5,2,8,1],ndmin=2)
b = np.array([1,3,5,7],ndmin=1)

print(a-b)
print()
s = np.subtract(a,b)
print('dimension: ',s.ndim)
print(s)

[[ 4 -1  3 -6]]

dimension:  2
[[ 4 -1  3 -6]]


#  Addition

In [60]:
import numpy as np

x = np.array([1,2,3,4])

y = x + 2
# or

z = np.add(x,2)
print(y,z)

# addition of twoo arrays

a1 = np.array([1,2,3,4,5],ndmin=2)
a2 = np.array([1,2,3,4,5],ndmin=2)

print(a1 + a2)
ad = np.add(a1,a2)
print(ad.ndim)
print('ans',ad)

# Total sum of array

print('total sum of a1 and a2 : ',np.sum([a1,a2]))
print('total sum of a1 and a2 column wise : ',np.sum([a1,a2],axis=0))
print('total sum of a1 and a2 rows wise : ',np.sum([a1,a2],axis=1)) # on1y applicable on 1d array

[3 4 5 6] [3 4 5 6]
[[ 2  4  6  8 10]]
2
ans [[ 2  4  6  8 10]]
total sum of a1 and a2 :  30
total sum of a1 and a2 column wise :  [[ 2  4  6  8 10]]
total sum of a1 and a2 rows wise :  [[1 2 3 4 5]
 [1 2 3 4 5]]


# Mean Median Standard deviation

In [66]:
# mean

me1 = np.array([12,41,23,71,2,6,90])
print('Mean : ',np.mean(me1))
# median

me2 = np.array([12,41,23,71,2,6,90])
print('Median : ',np.median(me1))
# standard deviation

me3 = np.array([12,41,23,71,2,6,90])
print('Standard deviation : ',np.std(me1))

Mean :  35.0
Median :  23.0
Standard deviation :  31.532296368734617


# Mod

In [24]:
# mtlb remainder return karega

m1 = np.array([2,4,6,8,1,3,5,7])
print(m1%3)
print(np.mod(m1,3))


[2 1 0 2 1 0 2 1]
[2 1 0 2 1 0 2 1]


# reciprocal

In [35]:
r1 = np.array([2/7,4/3,6/5,8/11])

r = np.reciprocal(r1)
print(r)

[3.5        0.75       0.83333333 1.375     ]


# CumSum

In [47]:
cs1 = np.array([2,4,6,8])

print(np.cumsum(cs1)) # it works as [2,2+4,2+4+6,2+4+6+8]

[ 2  6 12 20]


# Martix

In [5]:
# Difference b/w matrix & arrays
# it must be a 2d
import numpy as np

mat = np.matrix([[1,2,3,4],[5,6,7,8]])

print(mat,type(mat))
print()

ar = np.array([[1,2,3,4],[5,6,7,8]]) # main difference is shown in *

print(ar,type(ar))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.matrix'>

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [22]:
#multiplication in Matrix

mat = np.matrix([[1,2,3,4],[5,6,7,8]])
mat1 = np.matrix([[1],[2],[3],[4]])

print(mat*mat1)
print()
print(mat.dot(mat1))

[[30]
 [70]]

[[30]
 [70]]


In [29]:
# in Array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr*arr)

[[ 1  4  9 16]
 [25 36 49 64]]


In [33]:
# add / sub / div

x = np.matrix([[2,4,6,8],[1,3,5,7]])
y = np.matrix([[6,1,4,7],[2,5,9,8]])

print(x+y)
print()
print(x-y)
print()
print(x/y)



[[ 8  5 10 15]
 [ 3  8 14 15]]

[[-4  3  2  1]
 [-1 -2 -4 -1]]

[[0.33333333 4.         1.5        1.14285714]
 [0.5        0.6        0.55555556 0.875     ]]


# Functions Of Matrix

In [36]:
# Transpose

w = np.matrix([[2,4,6,8],[1,3,5,7]])

print(w,type(w))
print()
print(np.transpose(w)) # here rows will converted into coloumns and coloumns into rows
print()
print(w.T) # shortcut


[[2 4 6 8]
 [1 3 5 7]] <class 'numpy.matrix'>

[[2 1]
 [4 3]
 [6 5]
 [8 7]]

[[2 1]
 [4 3]
 [6 5]
 [8 7]]


In [37]:
# swapaxes

v = np.matrix([[2,4,6,8],[1,3,5,7]])

print(v)
print()
print(np.swapaxes(v,0,1)) # syntax(var, current axis, axis to convert) like it converts axis0--->axis1

[[2 4 6 8]
 [1 3 5 7]]

[[2 1]
 [4 3]
 [6 5]
 [8 7]]


In [40]:
# Inverse
# first it finds determinant d = 1/ad-bc * [a b =  1/ad-bc *   [d -b
#                                           c d]               -c a]

i = np.matrix([[1,2],[3,4]])

print(i)
print()
print(np.linalg.inv(i))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
# Power
# syntax(np.linalg.matrix_power(var,n)) where n=0 , n>0 ,n<0
# if n=0 it gives identitiy matrix I = [1 0
#                                       0 1]
# if n>0  gives power(multiplication)
# if n<0 gives inverse*power

p = np.matrix([[1,2],[3,4]])

print(np.linalg.matrix_power(p,3))
print()
print(np.linalg.matrix_power(p,0))
print()
print(np.linalg.matrix_power(p,-3))
print()

[[ 37  54]
 [ 81 118]]

[[1 0]
 [0 1]]

[[-14.75    6.75 ]
 [ 10.125  -4.625]]



In [48]:
# Determinant
# if two rows and coloumns is same det = 0

d = np.matrix([[2,3,4],
                [2,3,4],
                [1,2,3]])

print(np.linalg.det(d))

0.0


In [67]:
np.save

array([['E', 'B', '2', '2', '2', '1', '0', '0', '0', '6', '0', '6', '8']],
      dtype='<U11')