In [2]:
#copy use krnae sae original array ki copy save hojate hae given variable mae or oss variable mae agr changes karain
#tou oss sae original array pr fark nahi pare ga

#view koi data save nahi krta jis ki waja sae agr app koi changes krtae hain tou wo original array mae tou view wale beh change hoge

In [5]:
import numpy as np

x=np.array([1,2,3,4])
copy_of_x = x.copy()

x[1]=90
copy_of_x[3]=99

print(x)
print(copy_of_x)

[ 1 90  3  4]
[ 1  2  3 99]


In [6]:
import numpy as np

x=np.array([1,2,3,4])
view_of_x = x.view()

x[1]=90
view_of_x[3]=99

print(x)
print(view_of_x)#dono mae changes horahe hain

[ 1 90  3 99]
[ 1 90  3 99]
