# RANDOM

# i) Rand():



#the function is used to generate random values between 0 to 1


pakistani zoban mae kahin tou iss mae sirf positive numbers hongae b/w 0 to 1

In [2]:
import numpy as np
variable1=np.random.rand(4)
print(variable1)

[0.56983178 0.57364059 0.91008875 0.59839112]


In [5]:
import numpy as np
variable1=np.random.rand((3,5))
print(variable1)

[[0.46127695 0.72936093 0.85766878 0.86048368 0.13359413]
 [0.84955549 0.39334524 0.64130721 0.58546303 0.75659742]
 [0.97759467 0.55120618 0.69459932 0.6508574  0.68010564]]


# ii)Randn():

the function is used to generate random variable close to zero this may return negative and positive numbers as well

In [9]:
import numpy as np
var2=np.random.randn(4)
print(var2)

[-0.25831176  0.42794697 -1.29060873 -1.69190655]


In [10]:
import numpy as np
var2=np.random.randn((4,3))
print(var2)

[[ 0.80506535  0.9694366  -1.75487497]
 [ 0.12309799  1.97189211  0.31699355]
 [ 1.80148183  0.73860724 -1.11052581]
 [-0.71462287  1.49869643 -0.95365377]]


# iii)Ranf():

simple words mae kahin tou yae random value return krta hae between this interval[0,1)
jis mae 1 include nahi hota or 0 hota hae                                                                                  

In [13]:
import numpy as np
var3=np.random.ranf(4)#matlab we wont 4 elements
print(var3)

[0.45972704 0.99289834 0.33325492 0.50238335]


In [15]:
import numpy as np
var3=np.random.ranf((2,3))#matlab we wont 4 elements
print(var3)

[[0.811548   0.25287343 0.36963875]
 [0.37706574 0.2564061  0.47157728]]


# iv)Randint():


this function is used to generate random number between given range

In [22]:
import numpy as np
var4=np.random.randint(5,20,(3,3))#min,max , no_of_elements 
print(var4)

[[13 12 15]
 [13 19 16]
 [14  7  8]]


In [31]:
var5=np.random.randint([1, 5, 7], 10)
print(var5)

[3 6 7]


# a)Random.random

it return values randomly between 0 and 1 

In [33]:
import numpy as np
var6=np.random.random(5)
print(var6)

[0.50810048 0.86597883 0.23010401 0.31726096 0.4440269 ]


In [36]:
import numpy as np
var6=np.random.random((3,1))
print(var6)

[[0.48341969]
 [0.52209998]
 [0.02614088]]


# b)Random.normal

In [35]:
import numpy as np
var6=np.random.normal(5,1,5)#mean,standard_deviation,size
print(var6)

[5.16961312 5.12573286 5.35115099 5.62183045 5.06656711]


In [38]:
import numpy as np
var6=np.random.normal(5,1,(2,3))#mean,standard_deviation,size
print(var6)

[[5.8535093  5.06815415 5.47293728]
 [5.02960443 4.87092702 5.17585682]]
