# Data types

we use "dtype" to find data type of array in numpy

In [3]:
import numpy as np
var1=np.array([1,2,3,4])
print("data type: ",var1.dtype)

data type:  int32


In [4]:
import numpy as np
var1=np.array([1.0,2.3,3.5,4.5])
print("data type: ",var1.dtype)

data type:  float64


In [5]:
import numpy as np
var1=np.array(["a","b","c","d"])
print("data type: ",var1.dtype)

data type:  <U1


In [1]:
import numpy as np
var1=np.array([1,2.3,3.5,4.5,"a","b","c","d"])
print(var1)
print("data type: ",var1.dtype)

['1' '2.3' '3.5' '4.5' 'a' 'b' 'c' 'd']
data type:  <U32


now we will see how to convert data type of array in numpy

In [9]:
import numpy as np

x=np.array([1,2,3,4],dtype=np.int8)

print("data type:",x.dtype)

data type: int8


In [12]:
import numpy as np

x1=np.array([1,2,3,4],dtype="f")

print("data type:",x1.dtype)
print(x1)

data type: float32
[1. 2. 3. 4.]


In [ ]:
#we can also convert by using them as function

In [15]:
import numpy as np

x1=np.array([1,2,3,4])
new=np.float32(x1)

print("data type:",x1.dtype)
print("data type:",new.dtype)
print(new)
print(x1)

data type: int32
data type: float32
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
#as well as conversion is also possible by using astype

In [21]:
import numpy as np

x1=np.array([1,2,3,4])
new=x1.astype(float)

print("data type:",x1.dtype)
print("data type:",new.dtype)
print(new)
print(x1)

data type: int32
data type: float64
[1. 2. 3. 4.]
[1 2 3 4]
