In [6]:
import numpy as np

n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,9,10,11,12])
x=np.intersect1d(n1,n2)

print(x)

[5 6]


In [7]:
import numpy as np

n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,9,10,11,12])
x=np.intersect1d(n1,n2)

print(np.setdiff1d(n1,n2))

print(x)

[1 2 3 4]
[5 6]


In [12]:
import numpy as np

n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,9,10,11,12])

print(np.sum([n1,n2]))

74


In [13]:
import numpy as np

n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,9,10,11,12])

print(np.sum([n1,n2],axis=0))

[ 6  8 12 14 16 18]


In [14]:
import numpy as np

n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,9,10,11,12])

print(np.sum([n1,n2],axis=1))

[21 53]


In [20]:
import numpy as np

n1=np.array([[1,2,3],
            [4,5,6]])
n2=np.array([[5,6,9],
             [10,11,12]])

print(np.mean(n1))
print(np.std(n1))
print(n1.transpose())


3.5
1.707825127659933
[[1 4]
 [2 5]
 [3 6]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [22]:
import numpy as np

n1=np.array([1,2,3])
n2=np.array([5,6,9])
print(n1.dot(n2))

44


In [25]:
import numpy as np

n1=np.array([[1,2,3],[4,5,6]])
n2=np.array([5,6,9])
print(n1.dot(n2))

[ 44 104]


ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)